#!/bin/bash

export MPLCONFIGDIR="/srv/hopper/run/"
 
NAME="hopper.pw"                                  # Name of the application
DJANGODIR=/srv/hopper/hopper.pw/nsupdate             # Django project directory
SOCKFILE=/srv/hopper/run/gunicorn.sock  # we will communicte using this unix socket
PIDFILE=/srv/hopper/run/gunicorn.pid
USER=www-data                                       # the user to run as
GROUP=www-data                                      # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=nsupdate.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=nsupdate.wsgi                     # WSGI module name
 
echo "Starting $NAME"
 
# Activate the virtual environment
cd $DJANGODIR
source /srv/hopper/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /srv/hopper/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --log-level=debug \
  --bind=unix:$SOCKFILE \
  --pid $PIDFILE
